# Generated by Django 5.2.9 on 2025-12-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
    ]
